import { formatArea, formatDistance } from "@/lib/geo/format";
import type { Coordinate } from "@/lib/geo/types";

export function parseKmlPolygons(kml: string): Coordinate[][] {
  const document = new DOMParser().parseFromString(kml, "application/xml");
  if (document.querySelector("parsererror")) {
    throw new Error("The KMZ contains an invalid KML document.");
  }

  const rings = Array.from(
    document.getElementsByTagNameNS("*", "outerBoundaryIs"),
  )
    .map((boundary) =>
      boundary.getElementsByTagNameNS("*", "coordinates").item(0)?.textContent,
    )
    .filter((coordinates): coordinates is string => Boolean(coordinates))
    .map((coordinates) =>
      coordinates
        .trim()
        .split(/\s+/)
        .map((value) => value.split(",").slice(0, 2).map(Number) as Coordinate)
        .filter(
          ([longitude, latitude]) =>
            Number.isFinite(longitude) &&
            Number.isFinite(latitude) &&
            longitude >= -180 &&
            longitude <= 180 &&
            latitude >= -90 &&
            latitude <= 90,
        ),
    )
    .map((ring) => {
      const first = ring[0];
      const last = ring.at(-1);
      return first &&
        last &&
        first[0] === last[0] &&
        first[1] === last[1]
        ? ring.slice(0, -1)
        : ring;
    })
    .filter((ring) => ring.length >= 3);

  return rings;
}

export function createKml(
  closedRing: Coordinate[],
  areaSquareMetres: number,
  perimeterKilometres: number,
): string {
  const coordinates = closedRing
    .map(([longitude, latitude]) => `${longitude},${latitude},0`)
    .join(" ");

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>SolarDev Site Boundary</name>
    <Style id="site-boundary">
      <LineStyle><color>ff99d334</color><width>2</width></LineStyle>
      <PolyStyle><color>4099d334</color></PolyStyle>
    </Style>
    <Placemark>
      <name>SolarDev Site Boundary</name>
      <description><![CDATA[
        Gross area: ${formatArea(areaSquareMetres)}<br/>
        Perimeter: ${formatDistance(perimeterKilometres)}<br/>
        Generated by SolarDev GIS Site Check.
      ]]></description>
      <styleUrl>#site-boundary</styleUrl>
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>${coordinates}</coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
    </Placemark>
  </Document>
</kml>`;
}
